### ISSUE TITLE
Margo's blog post reflection on refugee crisis

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/pg-marketing#5]

**Comment by SKBW** [comment]
Unlikely to happen at this point, I think.
 Emailed her last week re: having the blog ready for Sunday. She's in Calgary on a family matter and said  next week would be better...

**Comment by PeaceGeeks** [comment]
That does not surprise me. Let's aim for another story at this point.




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad
